global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grpc"
    scrape_interval: 1s
    static_configs:
      - targets: ["docker.for.mac.localhost:8080"]

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "admin"
#      password: "admin"
